version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=qa_doc_generator
      - REDIS_URI=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
    restart: unless-stopped

  worker:
    build: .
    command: celery -A src.worker.tasks.celery_app worker --loglevel=info
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=qa_doc_generator
      - REDIS_URI=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: 