apiVersion: v1
kind: Secret
metadata:
  name: qa-doc-generator-secrets
type: Opaque
stringData:
  # These values should be replaced with actual secrets in a real deployment
  mongodb-uri: mongodb://mongodb-service:27017
  redis-uri: redis://redis-service:6379/0
  llm-api-key: your-llm-api-key-here 